# Generated by Django 3.0.4 on 2020-03-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residents',
            name='multipleFlats',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='residents',
            name='flatNo1',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='residents',
            name='flatNo2',
            field=models.CharField(max_length=5),
        ),
    ]
